### PR TITLE
general update

### PR DESCRIPTION
**Pull request by alphaolomi**
Hello @issyzac  @BenMaruchu 

I made some updates 

## Changes

- Updated deps
- removed package-lock
- Added Components folder structure
- Added Pages folder structure
- added CRA doc
- remove used files logo,,,
- added some coloring to components
- added some style

regards
@alphaolomi

### CODE REVIEW

**Comment by BenMaruchu** [comment]
@alphaolomi 

Hello, Nice work

Can you please pull changes and fix git conflicts.

Also I would like to ask why did you remove package-lock.json?

**Comment by alphaolomi** [comment]
i use yarn

**Comment by alphaolomi** [comment]
hey @BenMaruchu 
i fixed the conflicts

**Comment by BenMaruchu** [comment]
@alphaolomi it is not advisable to change tools for existing repo. like they way you have changed to yarn from npm .. 

Otherwise thanks for the pr

**Comment by BenMaruchu** [comment]
@alphaolomi it is not advisable to change tools for existing repo. like they way you have changed to yarn from npm .. 

Otherwise thanks for the pr

**Pull request merged**
